VOTING_DISABLED           = ENV['VOTING_DISABLED'] == 'true'
GENERATOR_DISABLED        = ENV['GENERATOR_DISABLED'] == 'true'
GENERATOR_SAVING_DISABLED = ENV['GENERATOR_SAVING_DISABLED'] == 'true'
GENERATOR_URL = ENV['GENERATOR_URL'].presence || 'http://localhost:3000'